# Generated by Django 4.2.3 on 2023-07-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_booking_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
